cv/urls.py
from django.urls import path
from .import views

app_name = "pages"

urlpatterns = [
    path('',views.Homepage.as_view(),name="homepage"),
    path('contact',views.Contact.as_view(),name="contact"),
    path('about',views.AboutUs.as_view(),name="about"),
    # path('learn/',views.LearnListView.as_view(),name="learn"),
    path('services/',views.Services.as_view(),name="service"),
]

learn/urls.py
from django.urls import path
from . import views
app_name = "learn"

urlpatterns = [
    path('',views.CourseListView.as_view(),name="course"),
    path('<slug>',views.CourseDetailView.as_view(),name="course-detail"),
    path('topic/<slug>',views.TopicDetailView.as_view(),name="topic-detail"),
]

projects/urls.py
from django.urls import path
from . import views
app_name = "project"

urlpatterns = [
    path('',views.ProjectListView.as_view(),name="list"),
    path('<slug>/',views.ProjectDetailView.as_view(),name="detail")
]

sammagafu/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('cv.urls')),
    path('learn/',include('learn.urls')),
    path('project/',include('projects.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cv/models.py
from django.db import models

# Create your models here.

learn/models.py
from django.db import models
from django.utils.translation import gettext as _
from django.utils import timezone
from django.utils.text import slugify

# Create your models here.
class CourseCategory(models.Model):
    category = models.CharField(verbose_name=_("Course Name"), max_length=160)
    slug = models.SlugField(_("slug"),editable=False)

    class Meta:
        """Meta definition for Course."""

        verbose_name = 'Course Category'
        verbose_name_plural = 'Courses Categories'


    def __str__(self):
        return self.category
    
    def save(self):
        if not self.pk:
            self.slug = slugify(self.category)
        super(CourseCategory,self).save()

    

class Course(models.Model):
    course = models.CharField(verbose_name=_("Course Name"), max_length=160)
    cover  = models.ImageField(verbose_name=_("Cover Image"), upload_to="cover/",blank=False,null=False,default="cover.png")
    slug = models.SlugField(_("slug"),editable=False,unique=True)
    description = models.TextField()
    views=models.IntegerField(default=0)
    published_date = models.DateField(_("Published Date"), auto_now=False, auto_now_add=True)
    category = models.ManyToManyField(CourseCategory)



    class Meta:
        """Meta definition for Course."""

        verbose_name = 'Course'
        verbose_name_plural = 'Courses'

    def __str__(self):
        return self.course

    def save(self):
        if not self.pk:
            self.slug = slugify(self.course)
        super(Course,self).save()

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('learn:course-detail', args=[str(self.slug)])


class  Topic(models.Model):
    course = models.ForeignKey(Course, verbose_name=_("course"), on_delete=models.CASCADE,null=True,related_name="topic")
    slug = models.SlugField(_("slug"),editable=False,null=True)
    topic  = models.CharField(_("Topic Name"), max_length=160)
    published_date = models.DateField(_("Published Date"),default=timezone.now())
    video  = models.CharField(_("Url for video"), max_length=400, blank=True)
    description = models.TextField()

    class Meta:

        verbose_name = 'Topic'
        verbose_name_plural = 'Topics'

    def __str__(self):
        return self.topic
    
    def save(self):
        self.slug = slugify(self.topic)
        super(Topic,self).save()

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('learn:topic-detail', args=[str(self.slug)])

projects/models.py
from django.db import models
from django.utils.translation import gettext as _
from django.utils.text import slugify
from django_quill.fields import QuillField

# Create your models here.

class ProjectCategory(models.Model):
    category = models.CharField(verbose_name=_("Project Category"), max_length=160)
    slug = models.SlugField(_("slug"),editable=False)

    def __str__(self):
        return self.category
    
    def save(self):
        self.slug = slugify(self.category)
        super(ProjectCategory,self).save()

    class Meta:
        """Meta definition for Project."""

        verbose_name = 'Project Category'
        verbose_name_plural = 'Project Categories'


class Project(models.Model):
    project = models.CharField(verbose_name=_("Project Name"), max_length=160)
    client = models.CharField(verbose_name=_("Clients Name"), max_length=100,blank=True,null=True)
    skills = models.CharField(verbose_name=_("skills"), max_length=100,blank=True,null=True)
    cover  = models.ImageField(verbose_name=_("Project Image"), upload_to="project/",blank=False,null=False,default="cover.png")
    slug = models.SlugField(_("slug"),editable=False,unique=True)
    content = QuillField(null=True,blank=True)
    views=models.IntegerField(default=0)
    published_date = models.DateField(_("Published Date"), auto_now=False, auto_now_add=True)
    category = models.ManyToManyField(ProjectCategory)

    """Model definition for Project."""

    # TODO: Define fields here

    class Meta:
        """Meta definition for Project."""

        verbose_name = 'Project'
        verbose_name_plural = 'Projects'

    def __str__(self):
        return self.project

    def save(self):
        self.slug = slugify(self.project)
        super(Project,self).save()

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('project:detail', args=[str(self.slug)])

cv/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from projects.models import Project
# Create your views here.

class Homepage(TemplateView):
    template_name = "index.html"

    def get_context_data(self, *args, **kwargs):
        context = super(Homepage, self).get_context_data(*args, **kwargs)
        context['project'] =  Project.objects.all()
        return context

class Contact(TemplateView):
    template_name = "contact.html"

class LearnListView(TemplateView):
    template_name = "learn.html"

class AboutUs(TemplateView):
    template_name = "about.html"

class Services(TemplateView):
    template_name = "services.html"

learn/views.py
from django.shortcuts import render
from django.views.generic import ListView,DetailView
from .models import Course,Topic,CourseCategory
# Create your views here.


class CourseListView(ListView):
    model = Course
    context_object_name = "course"
    template_name = "learn.html"

    def get_context_data(self,**kwargs):
        context = super(CourseListView,self).get_context_data(**kwargs)
        context['category'] = CourseCategory.objects.all()
        return context

class CourseDetailView(DetailView):
    model = Course
    context_object_name = "course"
    template_name = "learn-detail.html"

class TopicDetailView(DetailView):
    model = Topic
    context_object_name = "topic"
    template_name = "topic-detail.html"

projects/views.py
from typing import List
from django.shortcuts import render
from django.views.generic import ListView,DetailView
from . models import Project,ProjectCategory
# Create your views here.

class ProjectListView(ListView):
    template_name = "project.html"
    model = Project
    context_object_name = "project"

    def get_context_data(self,**kwargs):
        context = super(ProjectListView,self).get_context_data(**kwargs)
        context['category'] = ProjectCategory.objects.all()
        return context


class ProjectDetailView(DetailView):
    model=Project
    context_object_name = "project"
    template_name = "project-detail.html"

templates/base.html
<!DOCTYPE HTML>
{% load static %}
<html lang="en">
    <head>
        <!--=============== basic  ===============-->
        <meta charset="UTF-8">
        <title>Creativity and innovation.</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
        <meta name="robots" content="index, follow"/>
        <meta name="keywords" content="Social Media Management, Application Development, Project Development, Tanzania Developers, Tanzania Agency, Isidora Tanzania, Tanzania Digital Agency, Digital Agency in Tanzania,Marketing,Agency,Branding,Tanzania,Nature"/>
        <meta name="description" content="Samuel Fredrick Magafu | We design digital products,services, and eCommerce experiences for brands hence connect brands and technology"/>
        <!--=============== css  ===============-->
        <link type="text/css" rel="stylesheet" href="{% static 'css/reset.css' %}">
        <link type="text/css" rel="stylesheet" href="{% static 'css/plugins.css' %}">
        <link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}">
        <link type="text/css" rel="stylesheet" href="{% static 'css/color.css' %}">
        <link type="text/css" rel="stylesheet" href="{% static 'css/overide.css' %}">
        <link rel="https://cdn.rawgit.com/mfd/f3d96ec7f0e8f034cc22ea73b3797b59/raw/856f1dbb8d807aabceb80b6d4f94b464df461b3e/gotham.css">
        <!--=============== favicons ===============-->
        <link rel="shortcut icon" href="{% static 'images/favicon.svg' %}">
    </head>
    <body>
        <!--loader-->
        <div class="loader-wrap">
            <div class="pin"></div>
        </div>
        <!--loader end-->
        <!-- Main  -->
        <div id="main">
            <!-- header-->
            <header class="main-header">
                <a class="logo-holder" href="{% url 'pages:homepage' %}">
                <img src="{% static 'images/icon.svg' %}"  alt="">
                </a>
                <!-- nav-button-wrap-->
                <div class="nav-button but-hol">
                    <span  class="nos"></span>
                    <span class="ncs"></span>
                    <span class="nbs"></span>
                    <div class="menu-button-text">Menu</div>
                </div>
                <!-- nav-button-wrap end-->
                <div class="header-social">
                    <ul >
                        {% include 'includes/social.html' %}
                    </ul>
                </div>
            </header>
            <!--  header end -->
            <!--  navigation bar -->
            <div class="nav-overlay">
                <div class="tooltip color-bg">Close Menu</div>
            </div>
            <div class="nav-holder">
                <a class="header-logo" href="{% url 'pages:homepage' %}"><img src="{% static 'images/logo.svg' %}" alt=""></a>
                <div class="nav-title"><span>Menu</span></div>
                <div class="nav-inner-wrap">
                    <nav class="nav-inner sound-nav" id="menu">
                        {% include 'includes/navbar.html' %}
                    </nav>
                </div>
            </div>
            <!--  navigation bar end -->
            <!-- wrapper-->
            <div id="wrapper">
                <!-- scroll-nav-wrap-->
                <div class="scroll-nav-wrap fl-wrap">
                    <div class="scroll-down-wrap">
                        <div class="mousey">
                            <div class="scroller"></div>
                        </div>
                        <span>Scroll Down</span>
                    </div>
                    <nav class="scroll-nav">
                        {% include 'includes/navbar.html' %}
                    </nav>
                </div>
                
                {% block content %}
                    
                {% endblock content %}
                                   <!-- footer-->
                <div class="height-emulator fl-wrap"></div>
                <footer class="main-footer fixed-footer">
                    <!--footer-inner-->
                    <div class="footer-inner fl-wrap">
                        <div class="container">
                            <div class="partcile-dec" data-parcount="90"></div>
                            <div class="row">
                                <div class="col-md-2">
                                    <div class="footer-title fl-wrap">
                                        <span>Samuel </br>Magafu</span>
                                    </div>
                                </div>
                                <div class="col-md-5">
                                    
                                </div>
                                <div class="col-md-5">
                                    <div class="footer-header fl-wrap"><span>02.</span> Subscribe / Contacts</div>
                                    <!-- footer-box-->
                                    <div class="footer-box fl-wrap">
                                        <p>Want to be notified when we have published new tutorial. Just sign up and we'll send you a notification by email.</p>
                                        <div class="subcribe-form fl-wrap">
                                            <form id="subscribe" class="fl-wrap">
                                                <input class="enteremail" name="email" id="subscribe-email" placeholder="email" spellcheck="false" type="text">
                                                <button type="submit" id="subscribe-button" class="subscribe-button"><i class="fal fa-paper-plane"></i> Send </button>
                                                <label for="subscribe-email" class="subscribe-message"></label>
                                            </form>
                                        </div>
                                        <!-- footer-contacts-->
                                        <div class="footer-contacts fl-wrap">
                                            <ul>
                                                <li><i class="fal fa-phone text-lowercase"></i><span>Phone :</span><a href="tel:+255 788 419 991">+255 788 419 991</a></li>
                                                <li><i class="fal fa-envelope"></i><span>Email :</span><a href="mailto:hi@sammagafu.com?subject=Inquries">hi@sammagafu.com</a></li>
                                                <li><i class="fal fa-map-marker"></i><span>Address</span><a href="#">Changanyikeni, Dar es salaam - Tanzania</a></li>
                                            </ul>
                                        </div>
                                        <!-- footer end -->
                                        <!-- footer-socilal -->
                                        <div class="footer-socilal fl-wrap">
                                            <ul >
                                                {% include 'includes/social.html' %}
                                            </ul>
                                        </div>
                                        <!-- footer-socilal end -->
                                    </div>
                                    <!-- footer-box end-->
                                </div>
                            </div>
                        </div>
                    </div>
                    <!--footer-inne endr-->
                    <!--subfooter-->
                    <div class="subfooter fl-wrap">
                        <div class="container">
                            <!-- policy-box-->
                            <div class="policy-box">
                                <span>&#169; Sammagafu {% now 'Y' %}  /  All rights reserved. </span>
                            </div>
                            <!-- policy-box end-->
                            <a href="#" class="to-top color-bg"><i class="fal fa-angle-up"></i><span></span></a>
                        </div>
                    </div>
                    <!--subfooter end-->
                </footer>
                <!-- footer end-->
                <!-- contact-btn -->
                <a class="contact-btn color-bg" href="{% url 'pages:contact' %}"><i class="fal fa-envelope"></i><span>Get in Touch</span></a>
                <!-- contact-btn end -->
            </div>
            <!--   content end -->
            <!-- share-wrapper -->
            <div class="share-wrapper isShare">
                <div class="share-title"><span>Share</span></div>
                <div class="close-share soa"><span>Close</span><i class="fal fa-times"></i></div>
                <div class="share-inner soa">
                    <div class="share-container"></div>
                </div>
            </div>
            <!-- share-wrapper end -->
        </div>
        <!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-QLEGEEPF3R"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-QLEGEEPF3R');
</script>
        <!-- Main end -->
        <!--=============== scripts  ===============-->
        <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/plugins.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

templates/base_fixed.html
<!DOCTYPE HTML>
{% load static %}
<html lang="en">
    <head>
        <!--=============== basic  ===============-->
        <meta charset="UTF-8">
        <title>Get designed by the best</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
        <meta name="robots" content="index, follow"/>
        <meta name="keywords" content="Social Media Management, Application Development, Project Development, Tanzania Developers, Tanzania Agency, Isidora Tanzania, Tanzania Digital Agency, Digital Agency in Tanzania,Marketing,Agency,Branding,Tanzania,Nature"/>
        <meta name="description" content="Samuel Fredrick Magafu | We design digital products,services, and eCommerce experiences for brands hence connect brands and technology"/>
        <!--=============== css  ===============-->
        <link type="text/css" rel="stylesheet" href="{% static 'css/reset.css' %}">
        <link type="text/css" rel="stylesheet" href="{% static 'css/plugins.css' %}">
        <link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}">
        <link type="text/css" rel="stylesheet" href="{% static 'css/color.css' %}">
        <link type="text/css" rel="stylesheet" href="{% static 'css/overide.css' %}">
        <!--=============== favicons ===============-->
        <link rel="shortcut icon" href="{% static 'images/favicon.svg' %}">
    </head>
    <body>
        <!--loader-->
        <div class="loader-wrap">
            <div class="pin"></div>
        </div>
        <!--loader end-->
        <!-- Main  -->
        <div id="main">
            <!-- header-->
            <header class="main-header">
                <a class="logo-holder" href="{% url 'pages:homepage' %}">
                <img src="{% static 'images/icon.svg' %}"  alt="">
                </a>
                <!-- nav-button-wrap-->
                <div class="nav-button but-hol">
                    <span  class="nos"></span>
                    <span class="ncs"></span>
                    <span class="nbs"></span>
                    <div class="menu-button-text">Menu</div>
                </div>
                <!-- nav-button-wrap end-->
                <div class="header-social">
                    <ul >
                        {% include 'includes/social.html' %}   
                    </ul>
                </div>
            </header>
            <!--  header end -->
            <!--  navigation bar -->
            <div class="nav-overlay">
                <div class="tooltip color-bg">Close Menu</div>
            </div>
            <div class="nav-holder">
                <a class="header-logo" href="{% url 'pages:homepage' %}"><img src="{% static 'images/logo.svg' %}" alt=""></a> 
                <div class="nav-title"><span>Menu</span></div>
                <div class="nav-inner-wrap">
                    <nav class="nav-inner sound-nav" id="menu">
                        {% include 'includes/navbar.html' %}
                    </nav>
                </div>
            </div>
            <!--  navigation bar end -->
            <!--wrapper-->
            <div id="wrapper">
                <!-- Content-->
                <div class="content">
                    <div class="single-page-decor"></div>
                    <div class="single-page-fixed-row">
                        <div class="scroll-down-wrap">
                            <div class="mousey">
                                <div class="scroller"></div>
                            </div>
                            <span>Scroll Down</span>
                        </div>
                        <nav class="scroll-nav">
                            <ul>
                                {% include 'includes/navbar.html' %}
                            </ul>
                        </nav>
                    </div>
                    <!-- section-->
                   
                   {% block contents %}
                       
                   {% endblock contents %}
                       
                    <!-- section end-->
                </div>
                <!-- Content end -->
                <!-- footer-->
                <div class="height-emulator fl-wrap"></div>
                <footer class="main-footer fixed-footer">
                    <!--footer-inner-->
                    <div class="footer-inner fl-wrap">
                        <div class="container">
                            <div class="partcile-dec" data-parcount="90"></div>
                            <div class="row">
                                <div class="col-md-2">
                                    <div class="footer-title fl-wrap">
                                        <span>Samuel </br>Magafu</span>
                                    </div>
                                </div>
                                <div class="col-md-5">
                                </div>
                                <div class="col-md-5">
                                    <div class="footer-header fl-wrap"><span>02.</span> Subscribe / Contacts</div>
                                    <!-- footer-box-->
                                    <div class="footer-box fl-wrap">
                                        <p>Want to be notified when we launch a new template or an udpate. Just sign up and we'll send you a notification by email.</p>
                                        <div class="subcribe-form fl-wrap">
                                            <form id="subscribe" class="fl-wrap">
                                                <input class="enteremail" name="email" id="subscribe-email" placeholder="email" spellcheck="false" type="text">
                                                <button type="submit" id="subscribe-button" class="subscribe-button"><i class="fal fa-paper-plane"></i> Send </button>
                                                <label for="subscribe-email" class="subscribe-message"></label>
                                            </form>
                                        </div>
                                        <!-- footer-contacts-->
                                        <div class="footer-contacts fl-wrap">
                                            <ul>
                                                <li><i class="fal fa-phone text-lowercase"></i><span>Phone :</span><a href="tel:+255 788 419 991">+255 788 419 991</a></li>
                                                <li><i class="fal fa-envelope"></i><span>Email :</span><a href="mailto:hi@sammagafu.com?subject=Inquries">hi@sammagafu.com</a></li>
                                                <li><i class="fal fa-map-marker"></i><span>Address</span><a href="#">Changanyikeni, Dar es salaam - Tanzania</a></li>
                                            </ul>
                                        </div>
                                        <!-- footer end -->
                                        <!-- footer-socilal -->
                                        <div class="footer-socilal fl-wrap">
                                            <ul >
                                                {% include 'includes/social.html' %}
                                            </ul>
                                        </div>
                                        <!-- footer-socilal end -->
                                    </div>
                                    <!-- footer-box end-->
                                </div>
                            </div>
                        </div>
                    </div>
                    <!--footer-inne endr-->
                    <!--subfooter-->
                    <div class="subfooter fl-wrap">
                        <div class="container">
                            <!-- policy-box-->
                            <div class="policy-box">
                                <span>&#169; Sammagafu {% now 'Y' %}  /  All rights reserved. </span>
                            </div>
                            <!-- policy-box end-->
                            <a href="#" class="to-top color-bg"><i class="fal fa-angle-up"></i><span></span></a>
                        </div>
                    </div>
                    <!--subfooter end-->
                </footer>
                <!-- footer end-->
                <!-- contact-btn -->
                <a class="contact-btn color-bg" href="{% url 'pages:contact' %}"><i class="fal fa-envelope"></i><span>Get in Touch</span></a>
                <!-- contact-btn end -->
            </div>
            <!--   content end -->
            <!-- share-wrapper -->
            <div class="share-wrapper isShare">
                <div class="share-title"><span>Share</span></div>
                <div class="close-share soa"><span>Close</span><i class="fal fa-times"></i></div>
                <div class="share-inner soa">
                    <div class="share-container"></div>
                </div>
            </div>
            <!-- share-wrapper end -->
        </div>
        <!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-QLEGEEPF3R"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-QLEGEEPF3R');
</script>
        <!-- Main end -->
        <!--=============== scripts  ===============-->
        <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/plugins.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

templates/includes/navbar.html
<ul>
    <li><a class="scroll-link" href="{% url 'pages:homepage' %}">homepage</a></li>
    <li><a class="scroll-link" href="{% url 'learn:course' %}">Learn</a></li>
    <li><a class="scroll-link" href="{% url 'project:list' %}">Projects</a></li>
    <li><a class="scroll-link" href="{% url 'pages:service' %}">Services</a></li>
    <li><a class="scroll-link" href="{% url 'pages:about' %}">About</a></li>
</ul>

templates/includes/social.html
<li><a href="https://www.instagram.com/samvsuel/" target="_blank"><i class="fab fa-instagram"></i></a></li>
<li><a href="https://github.com/code2913" target="_blank"><i class="fab fa-github"></i></a></li>
<li><a href="https://www.linkedin.com/in/samvsuel/" target="_blank"><i class="fab fa-linkedin"></i></a></li>
<li><a href="https://twitter.com/samvsuel" target="_blank"><i class="fab fa-twitter"></i></a></li>

templates/learn-detail.html
{% extends 'base_fixed.html' %}
{% load static %}


{% block contents %}
<section class="parallax-section fw-parallax" data-scrollax-parent="true">
    <div class="bg par-elem"  data-bg="{{ course.cover.url }}" data-scrollax="properties: { translateY: '30%' }"></div>
    <div class="overlay"></div>
    <div class="pattern-bg"></div>
    <div class="container">
        <div class="section-title">
            <h2>{{ course.course }}</h2>
            <p> {{ course.description }}</p>
            <div class="horizonral-subtitle"><span># LEARN</span></div>
        </div>
    </div>
    <div class="hero-start-button-wrap">
        <div class="container">
            <a href="#sec1" class="custom-scroll-link hero-start-button"><span>Let's Start</span> <i class="fal fa-long-arrow-down"></i></a>
        </div>
    </div>
</section>

<section class="dark-bg">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="hidden-info fl-wrap">
                    <div class="hidden-works-list fl-wrap">
                        {% for topic in course.topic.all %}
                        <div class="hidden-works-item fl-wrap">
                            <div class="hidden-works-item-text">
                                <h3><a href="{{topic.get_absolute_url }}">{{ topic.topic }}</a></h3>
                                <p>{{ topic.description }}</p>
                            </div>
                        </div>
                        {% endfor %} 
                    </div>
                    <!-- <div class="hidden-info-pagination m-30"><a href="#"><span>Next Page</span><i class="fal fa-arrow-right"></i></a></div> -->
    
                </div>
            </div>
            <div class="col-md-4 no-padding">
            </div>
        </div>
    </div>
    <!-- hidden-info-wrap end -->
    <div class="fl-wrap limit-box"></div>
</section>

{% endblock contents %}
    

templates/topic-detail.html
{% extends 'base_fixed.html' %}
{% load static %}

{% block contents %}
<div id="wrapper" class="single-page-wrap">
    <!-- Content-->
    <div class="content">

        <section data-scrollax-parent="true" id="sec1">
            <!-- <div class="section-subtitle right-pos" data-scrollax="properties: { translateY: '-250px' }" style="transform: translateZ(0px) translateY(92.1677px); font-size: 172.353px;"><span>//</span>Project Title</div> -->
            <div class="container">
                <div class="fl-wrap">
                    <div class="row">
                        <div class="col-md-4">
                            <div class="fixed-column l-wrap" style="z-index: auto; position: static; top: auto;">
                                <div class="pr-title fl-wrap">
                                    <h3>{{ topic.topic }}</h3>
                                    <span>{{ topic.description}}</span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-8">
                            <div class="details-wrap fl-wrap">
                             {{ topic.video|safe }}
                            </div>
                        </div>
                    </div>
                    <div class="limit-box fl-wrap"></div>
                </div>
                <!-- det box end-->
            </div>
        </section>
 
    </div>
    <!-- Content end -->
    <!-- footer-->
    <div class="height-emulator fl-wrap" style="height: 664px;"></div>
</div>
{% endblock contents %}